<?php if ($this->getCheckout()->getStepData('customstep', 'complete')): ?>
    <dt class="complete">
        <?php echo $this->__('Insurance') ?><span class="changelink"> <span class="separator">|</span> <a
                    href="#customstep"
                    onclick="checkout.changeSection('opc-customstep'); return false;"><?php echo $this->__('Change') ?></a></span>
    </dt>
    <dd class="complete">
        <address>
            <?php $insurance = $this->getQuote()->getInsurance(); ?>

            <?php if($insurance != null): ?>
                <?php echo $this->__('Сost: ') ?>
                <span class="price">$<?php echo $insurance ?></span>
            <?php else: ?>
                <?php echo $this->__('Not added') ?>
            <?php endif; ?>
        </address>
    </dd>
<?php else: ?>
    <dt>
        <?php echo $this->__('Insurance') ?>
    </dt>
<?php endif; ?>