<?php if($this->isModuleEnable()): ?>
    <?php $methods = $this->getShippingMethods(); ?>
    <?php foreach ($methods as $method): ?>
        <div id="<?php echo $method; ?>" hidden="hidden">
            <input type="checkbox" name="add_insurance" id="add_insurance" value="enabled" class="checkbox">
            <label for="add_insurance">Add insurance</label>
            <p>Cost:
                <span class="price">$<?php echo $this->getInsuranceCost($method); ?></span>
            </p>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<script type="text/javascript">
    var selectedMethod = null;

    document.addEventListener('DOMNodeInserted', DOMNodeInsertedHandler);
    $j('li').on('change', 'input[name="shipping_method"]', function () {
        updateSelectedMethod(this);
    });

    function DOMNodeInsertedHandler() {
        var radiobutton = document.querySelector('input[name="shipping_method"]:checked');
        if (radiobutton != null) {
            updateSelectedMethod(radiobutton);
        }
    }

    function updateSelectedMethod(radiobutton) {
        var id = getId(radiobutton);
        var method = document.getElementById(id);
        if (method != null) {
            method.removeAttribute('hidden');
        }
        if ((selectedMethod != null) && (selectedMethod !== method)) {
            selectedMethod.setAttribute('hidden', 'hidden');
        }
        selectedMethod = method;
    }

    function getId(radiobutton) {
        return radiobutton.value.split('_')[0];
    }
</script>
