<?php if($this->isModuleEnable()): ?>
    <?php $method = $this->getShippingMethod(); ?>
    <fieldset>
        <ul class="form-list">
            <li id="insurance">
                <fieldset>
                    <ul>
                        <?php if($this->isShippingMethodEnable($method)): ?>
                            <li class="control">
                                <input type="checkbox" name="add_insurance" id="add_insurance" value="enabled" class="checkbox">
                                <label for="add_insurance">Add insurance</label>
                            </li>
                            <li class="wide">
                                <label for="insurance">
                                    <?php echo $this->__('Сost of insurance: ') ?>
                                    <span class="price">$<?php echo $this->getInsuranceCost($method); ?></span>
                                </label>
                            </li>
                        <?php else: ?>
                            <li class="wide">
                                <label for="insurance">
                                    <?php echo $this->__('Insurance is disabled for this shipping method.') ?>
                                </label>
                            </li>
                        <?php endif; ?>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </fieldset>
<?php else: ?>
    <li class="wide">
        <label for="insurance">
            <?php echo $this->__('Insurance is not available now.') ?>
        </label>
    </li>
<?php endif; ?>